version: '2'

services:
  rc-admin-tools:
    build: .
    command: npm run server
    container_name: rc-admin-tools
    restart: unless-stopped
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
